pipeline {
    agent any

    environment {
        S3_BUCKET = 'sagar0211'
        ZIP_FILE = 'blogss.zip'
        DOCKER_IMAGE = 'React-app:v1.0'
        SERVER_IP = '152.58.30.60'
        SERVER_USER = 'ec2-user'
        SERVER_SSH_KEY = credentials('docker-registry-credentials')
    }

    stages {
        stage('Download Zip from S3') {
            steps {
                script {
                    sh "aws s3 cp s3://${S3_BUCKET}/${ZIP_FILE} ."
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }

        stage('Push Docker Image to Server') {
            steps {
                script {
                    sh "docker save ${DOCKER_IMAGE} | gzip | ssh -i ${SERVER_SSH_KEY} ${SERVER_USER}@${SERVER_IP} 'gunzip | docker load'"
                }
            }
        }
    }
}
