pipeline {
    agent any

    stages {
        stage('Fetch ZIP File') {
            steps {
                // Use a shell command or a Jenkins plugin (e.g., AWS CLI for S3) to download the ZIP file
                sh 'wget -O your-app.zip https://example.com/path/to/your-app.zip'
            }
        }

        stage('Unzip React App') {
            steps {
                sh 'unzip your-app.zip -d react-app'  // Unzip the ZIP file to a directory
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    def imageName = 'your-docker-image-name:your-tag'
                    def dockerFile = 'Dockerfile'  // Path to your Dockerfile

                    // Build Docker image
                    docker.build(imageName, "-f ${dockerFile} .")

                    // Push Docker image to a registry (e.g., Docker Hub)
                    docker.withRegistry('https://your-docker-registry.com', 'your-docker-registry-credentials') {
                        docker.image(imageName).push()
                    }
                }
            }
        }
    }
}
