pipeline {
    agent any
    stages {
        stage('Create IAM User') {
            steps {
                withAWS(credentials: 'bob', region: 'ap-south-1') 
                {
                    sh 'python pipeline7/create_policy/create_policy.py'
                }
            }
        }
    }
}
