pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                withAWS(credentials: 'bob', region: 'ap-south-1') 
                {
                    sh 'python pipeline8.1/create_(policy,user,atta.policy).py'
                }
            }
        }
      stage('build') {
            steps {
                withAWS(credentials: 'bob', region: 'ap-south-1') 
                {
                    sh 'python pipeline8.1/create_(policy,user,atta.policy).py'
                }
            }
        }
      stage('build') {
            steps {
                withAWS(credentials: 'bob', region: 'ap-south-1') 
                {
                    sh 'python pipeline8.1/create_(policy,user,atta.policy).py'
                }
            }
        }
    }
}
