pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
        AWS_ACCESS_KEY_ID     = credentials('b6eeb0c5-6a67-4a2b-aab1-5ab5db3ce00f')
        AWS_ACCESS_KEY_ID_USR = ' AKIAZRICDOIC5FCCXJVL'
        AWS_ACCESS_KEY_ID_PSW  = 'HpM4WuNk7abr3OMkWYvXY45rjewyuoLg/EEfN3Be' 
        IAM_USERNAME = 'tiger2'
        GIT_REPO_URL = 'https://github.com/Shub-123456/Shub_1234.git'
    }
  stages{
      stage('Adding git credentials'){
            steps {
                script {
                    git branch: 'main', credentialsId: 'bob2', url: env.GIT_REPO_URL
                }
            }
        }
      stage('Create IAM User') {
            steps {
                script {
                    sh """
                        aws iam create-user --user-name ${env.IAM_USERNAME}
                     """
                }
            }
        }
    }
  post{
    success{
      sh'python Gmail/success.py '
    }
    failure{
      sh'python Gmail/failed.py '
    }
  }
  }
